version: "3.3"
services:
    app:
        stdin_open: true
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - './:/app'
            - '/app/node_modules'
        stdin_open: true # docker run -i
        tty: true        # docker run -t